### ISSUE TITLE
Can we get ban from Discord

### ISSUE THREAD

**Issue by Boctuline** [Flam3rboy/discord-bot-client#47]
Hello, can we get ban from Discord because of the client ? Thanks for your answer !

**Comment by SiaALT** [comment]
> Hello, can we get ban from Discord because of the client ? Thanks for your answer !
### Probably not.
** Since discord is really gonna look into who is hacking. Although this is actually against the Discord TOS. So yes you can be banned but most likely not since Discord Staff/Developers are much more busy doing updates and etc.**

**Comment by mostidaniel** [comment]
Based on what I know, Discord TOS bans the usage of "user-bots" and "self-bots". This generally means bots running on top of normal user accounts instead of using the intended bot accounts. I don't think the same applies vice versa.

Therefore, I don't think it is bannable. As long as the app uses official APIs to connect and interact with Discord, and we use bot accounts instead of normal user accounts, we should be safe.

**Comment by xNaCly** [comment]
No you cant get banned for using this client.

**Comment by Boctuline** [comment]
Thanks for your answers !
